repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 25.3.5
    values:
      - brokers: 5
      - image:
          tag: 3.5.2-debian-11-r0
      - auth:
          clientProtocol: SASL_PLAINTEXT
          interBrokerProtocol: SASL_PLAINTEXT
    
  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    values:
      - brokers: 1
      - auth:
          clientProtocol: PLAINTEXT
          interBrokerProtocol: PLAINTEXT
          enabled: false