apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.deployment.service.targetPort }}
  type: ClusterIP